name: Android NDK Build
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1.5.0
      with:
        ndkVersion: '27.0.12077973'

    - name: Setup build environment
      run:
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    - name: Build
      run:
        bash build-android.sh